# These are queried by the client build script, check that

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=io.github.dewsmith0.mcahelp.client

# Dependencies
fabric_api_version=0.141.4+1.21.11